config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users , :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations"}
  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  get 'static_pages/order_created'

  mount ActionCable.server => '/cable'

   root 'static_pages#landing_page'

  get '/products/id:', to: 'products#show'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments

	validates :name, :price, :image_url, :color, presence: true
	validates :price, numericality: true

	def highest_rating_comment
		comments.rating_desc.first
	end

	def lowest_rating_comment
		comments.rating_asc.first
	end

	def average_rating
		comments.average(:rating).to_f
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, :except => [:show, :index]
	load_and_authorize_resource
	respond_to :json, :html


	# GET /products
	# GET /products.json
	def index
		if params[:q]
			search_term = params[:q]
			@products = Product.where("name ilike ?", "%#{search_term}%")
		else
			@products = Product.all
		end
		respond_with @products
	end

	# GET /products/1
	# GET /products/1.json
	def show
		@comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
	end

	# GET /products/new
	def new
		if signed_in? && current_user.admin?
			@product = Product.new 
		end
	end

	# GET /products/1/edit
	def edit
	end

	# POST /products
	# POST /products.json
	def create
		if signed_in? && current_user.admin?
			@product = Product.new(product_params)

			respond_to do |format|
				if @product.save
					format.html { redirect_to @product, notice: 'Product was successfully created.' }
					format.json { render :show, status: :created, location: @product }
				else
					format.html { render :new }
					format.json { render json: @product.errors, status: :unprocessable_entity }
				end
			end
		end
	end

	# PATCH/PUT /products/1
	# PATCH/PUT /products/1.json
	def update
		if signed_in? && current_user.admin?
			respond_to do |format|
				if @product.update(product_params)
					format.html { redirect_to @product, notice: 'Product was successfully updated.' }
					format.json { render :show, status: :ok, location: @product }
				else
					format.html { render :edit }
					format.json { render json: @product.errors, status: :unprocessable_entity }
				end
			end
		end
	end

	# DELETE /products/1
	# DELETE /products/1.json
	def destroy
		if signed_in? && current_user.admin?
			@product.destroy
			respond_to do |format|
				format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
				format.json { head :no_content }
			end
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_product
			@product = Product.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def product_params
			params.require(:product).permit(:id, :name, :description, :image_url, :color, :price)
		end

end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
		count = Product.count
		max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"product/all-#{count}-#{max_updated_at}"
	end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
    <div class="row">
      <hr>
      <p>
        <%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
        <% if signed_in? && current_user.admin? %>
          <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
          <%#= link_to 'Destroy', product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </p>
      <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= comment.body %></p>
    </div>
  <% end %>
</div>

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= form_for(@product) do |f| %>
        <% if @product.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
            <% @product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        
          <div class="field form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, class:"form-control" %>
          </div>
          <div class="field form-group">
            <%= f.label :description %><br>
            <%= f.text_area :description, class:"form-control" %>
          </div>
          <div class="field form-group">
            <%= f.label :image_url %><br>
            <%= f.text_field :image_url, class:"form-control" %>
          </div>
          <div class="field form-group">
            <%= f.label :color %><br>
            <%= f.text_field :color, class:"form-control" %>
          </div>
          <div class="field form-group">
            <%= f.label :price %><br>
            <%= f.text_field :price, step: 0.01, class:"form-control" %>
          </div>
          <div class="actions">
            <%= f.submit class:"btn btn-default" %>
          </div>
        </div>
      </div> 
    </div>
  <% end %>
</div>

app/views/products/_new_comment.html.erb
<div class="product-review">
  <% if signed_in? %>
    <h4>Add a review:</h4>
    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
      <div class="form-group">
        <%= f.label :body, "Comments" %><br>
        <%= f.text_area :body, class: "form-control", :required => true %>
      </div>
      <p>
        <div class="rating"></div>
      </p>  
      <p>
        <%= f.submit class: "btn btn-primary" %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/products/_product.html.erb
 <div class="container-fluid">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-sm-2 col-md-4">
        <%= image_tag(product.image_url, class: "img-responsive") %>
        <h3><%= product.name %></h3>
        <p><%= product.description %></p>
        <p><%= product.color %></p>
        <p>Average Rating: <div class="rated" data-score="<%= product.average_rating %>"> </div> </p>
        <strong>$<%= product.price %></strong><br>
        <%= link_to 'Show', product, class: "btn btn-default" %>

        <% if signed_in? && current_user.admin? %>
          <%= link_to 'Edit', edit_product_path(product), class: "btn btn-default" %>
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
        <% end %>
      </div><!-- /col -->
      <% end %>
    </div>
  </div>

app/views/products/edit.html.erb
<div class="container">
  <h1>Editing Product</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="container">

	<h1>Listing Products</h1>
	<% cache (cache_key_for_products) do %>
	<%= render 'product' %>
	<% end %> 
	<br>
	<% if signed_in? && current_user.admin? %>
		<%= link_to 'New Product', new_product_path, class: "btn btn-default" %>
	<% end %>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1>New Product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container">

  <div class="row data-product-id=<%= @product.id %>">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <% cache @product do %>
        <%= image_tag(@product.image_url, class: "img-zoom img-responsive", data_zoom_image: @product.image_url ) %>
        <div class="caption">
          <h3><%= @product.name %></h3>
          <p>
            <strong>Description:</strong>
            <%= @product.description %>
          </p>
          <p>
            <strong>Color</strong>
            <%= @product.color %>
          </p>

          <p>
            <strong>Price</strong>
            <%= @product.price %>
          </p>

          <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"> </div> </p>

          <% end %>

          <%= form_tag "/payments/create" do %>
            <%= render partial: "shared/stripe_checkout_button" %>
          <% end %>

          
          <%= render 'new_comment' %>

        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-6 col-md-offset-2">
      <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
      
      <%= render 'comments' %>
      <div class="pager">
      <%= will_paginate @comments, render: BootstrapPagination::Rails %>
      </div>


      <div>
        

      </div>
    </div>
    
  </div>





<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
</div>