config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users , :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations"}
  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  get 'static_pages/order_created'

  mount ActionCable.server => '/cable'

   root 'static_pages#landing_page'

  get '/products/id:', to: 'products#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nameofapp</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
</head>
<body>
	<header>
		<% if alert %>
		  <div class="alert bg-warning alert-dismissible" role="alert">
		  	<button type="button" class="close" data-dismiss="alert" aria-label="Close"<span aria-hidden="true">&times;</span></button>
		  	<%= alert %></div>
		<% end %> 
		<% if notice %>
		  <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		  	<%= notice %></div>
		<% end %>

		<!-- Second navbar for sign in -->
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
          <ul class="nav navbar-nav navbar-right">
            <li>
		    			<%= link_to 'Home', root_path %>
      			</li>
      			<li>
      				<%= link_to 'Products', products_path %>
      			</li>
      			<li>
      				<%= link_to 'About', static_pages_about_path %>
      			</li>
      			<li>
      				<%= link_to 'Contact', static_pages_contact_path %>
      			</li>

      			<% if user_signed_in? %>
      			<%= link_to('Sign out', destroy_user_session_path, :method => :delete, class: 'btn btn-default btn-outline btn-circle') %>
    				<% else %>
    				
      			<li>
              <a class="btn btn-default btn-outline btn-circle collapsed"  data-toggle="collapse" href="#nav-collapse2" aria-expanded="false" aria-controls="nav-collapse2">Sign in</a>
            </li>
            <% end %>
          </ul>
          <%= form_tag("/products", method: "get", class: "navbar-form") do %>
  					<%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search") %>
  					<%= submit_tag("Search", class: "btn btn-success" )%>
					<% end %>

          <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-collapse2">
 						
            <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: "navbar-form navbar-right form-inline"}) do |f| %>
              <div class="form-group">
                <%= f.label :email, class: "sr-only" %>
          			<%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email"%>
              </div>
              <div class="form-group">
                <%= f.label :password, class: "sr-only" %>
          			<%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password" %>
              </div>
              <%= f.submit "Sign in", class: "btn btn-success" %>
              <%= link_to "Sign up", new_registration_path(resource_name) %>  
          </div>

          <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->
   
	</header>
	<div class="page-wrap">
    
    <%= yield %>

  </div>
  <footer class="footer">
    <div class="container"> 
      <p>&copy; 2016 Bike Berlin</p>
    </div>
  </footer>

</body>
</html>